site_name: Industrial Ontology Community Resources
site_url: https://ontology_training.github.io
theme:
    name: material
    logo: images/equonto_logo.svg
    favicon: images/equonto_logo.svg
    custom_dir: overrides 
    features: 
    - navigation.footer
extra:
  social:
    - icon: equonto_logo
    - icon: nlp_logo
      link: https://nlp-tlp.org/
    - icon: fontawesome/brands/github
      link: https://github.com/Equonto
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
    - Home: index.md 
    - Training Resources: existing_training.md 

